{{
    config(
        materialized='ephemeral'
    )
}}

{% set batch_id = 'XXXX111' %} -- could pass in a var(), query dynamically from API table like you're doing now, etc.

SELECT
 '{{batch_id}}' AS BATCH_ID -- could also get batch ID from a control table, UUID etc.
, URL
, TRY_TO_DOUBLE(RISK_EXPOSURE_INDEX) AS RISK_EXPOSURE_INDEX_X
, TRY_TO_DOUBLE(RISK_EXPOSURE_INDEX) AS RISK_EXPOSURE_INDEX
, TRY_TO_DOUBLE(NATURAL_DISASTER_INDEX) AS NATURAL_DISASTER_INDEX_X
, TRY_TO_DOUBLE(NATURAL_DISASTER_INDEX) AS NATURAL_DISASTER_INDEX
, DEACTIVATED
, POSTAL_CODE
, STREET
, INCIDENT_ALERTING_PROFILE
, TRY_TO_DOUBLE(LONGITUDE) AS LONGITUDE_X
, TRY_TO_DOUBLE(LONGITUDE) AS LONGITUDE
, TRY_TO_DOUBLE(LATITUDE) AS LATITUDE_X
, TRY_TO_DOUBLE(LATITUDE) AS LATITUDE
, CITY
, NODE_TYPE
, NODE_NAME
, COUNTRYISO3
, EXTERNAL_ID
, SUB_SECTORS
, TRY_TO_DOUBLE(FLOOD) AS FLOOD_X
, TRY_TO_DOUBLE(FLOOD) AS FLOOD
, TRY_TO_DOUBLE(FLASH_FLOOD) AS FLASH_FLOOD_X
, TRY_TO_DOUBLE(FLASH_FLOOD) AS FLASH_FLOOD
, TRY_TO_DOUBLE(WAR) AS WAR_X
, TRY_TO_DOUBLE(WAR) AS WAR
, TRY_TO_DOUBLE(TERRORISM) AS TERRORISM_X
, TRY_TO_DOUBLE(TERRORISM) AS TERRORISM
, TRY_TO_DOUBLE(CIVIL_UNREST) AS CIVIL_UNREST_X
, TRY_TO_DOUBLE(CIVIL_UNREST) AS CIVIL_UNREST
, TRY_TO_DOUBLE(OPERATIONAL_INDEX) AS OPERATIONAL_INDEX_X
, TRY_TO_DOUBLE(OPERATIONAL_INDEX) AS OPERATIONAL_INDEX
, TRY_TO_DOUBLE(POLITICAL_VIOLENCE_INDEX) AS POLITICAL_VIOLENCE_INDEX_X
, TRY_TO_DOUBLE(POLITICAL_VIOLENCE_INDEX) AS POLITICAL_VIOLENCE_INDEX
, TRY_TO_DOUBLE(SOCIO_POLITICAL_INDEX) AS SOCIO_POLITICAL_INDEX_X
, TRY_TO_DOUBLE(SOCIO_POLITICAL_INDEX) AS SOCIO_POLITICAL_INDEX
, TRY_TO_DOUBLE(SUSTAINABILITY_INDEX) AS SUSTAINABILITY_INDEX_X
, TRY_TO_DOUBLE(SUSTAINABILITY_INDEX) AS SUSTAINABILITY_INDEX
, TRY_TO_DOUBLE(RISK_TO_INDIVIDUALS_INDEX) AS RISK_TO_INDIVIDUALS_INDEX_X
, TRY_TO_DOUBLE(RISK_TO_INDIVIDUALS_INDEX) AS RISK_TO_INDIVIDUALS_INDEX
, TRY_TO_DOUBLE(EARTHQUAKE) AS EARTHQUAKE_X
, TRY_TO_DOUBLE(EARTHQUAKE) AS EARTHQUAKE
, TRY_TO_DOUBLE(TORNADO) AS TORNADO_X
, TRY_TO_DOUBLE(TORNADO) AS TORNADO
, TRY_TO_DOUBLE(VOLCANO) AS VOLCANO_X
, TRY_TO_DOUBLE(VOLCANO) AS VOLCANO
, TRY_TO_DOUBLE(EXTRATROPICAL_CYCLONE) AS EXTRATROPICAL_CYCLONE_X
, TRY_TO_DOUBLE(EXTRATROPICAL_CYCLONE) AS EXTRATROPICAL_CYCLONE
, TRY_TO_DOUBLE(HAIL) AS HAIL_X
, TRY_TO_DOUBLE(HAIL) AS HAIL
, TRY_TO_DOUBLE(TROPICAL_CYCLONE) AS TROPICAL_CYCLONE_X
, TRY_TO_DOUBLE(TROPICAL_CYCLONE) AS TROPICAL_CYCLONE
, TRY_TO_DOUBLE(LIGHTNING) AS LIGHTNING_X
, TRY_TO_DOUBLE(LIGHTNING) AS LIGHTNING
, TRY_TO_DOUBLE(WILDFIRE) AS WILDFIRE_X
, TRY_TO_DOUBLE(WILDFIRE) AS WILDFIRE
, TRY_TO_DOUBLE(TSUNAMI) AS TSUNAMI_X
, TRY_TO_DOUBLE(TSUNAMI) AS TSUNAMI
, TRY_TO_DOUBLE(STORM_SURGE) AS STORM_SURGE_X
, TRY_TO_DOUBLE(STORM_SURGE) AS STORM_SURGE
, TRY_TO_DOUBLE(CORRUPTION) AS CORRUPTION_X
, TRY_TO_DOUBLE(CORRUPTION) AS CORRUPTION
, TRY_TO_DOUBLE(LAW_ENFORCEMENT) AS LAW_ENFORCEMENT_X
, TRY_TO_DOUBLE(LAW_ENFORCEMENT) AS LAW_ENFORCEMENT
, LABOUR_STRIKE
, TRY_TO_DOUBLE(COUNTERFEIT_THREAT) AS COUNTERFEIT_THREAT_X
, TRY_TO_DOUBLE(COUNTERFEIT_THREAT) AS COUNTERFEIT_THREAT
, TRY_TO_DOUBLE(AVIATION) AS AVIATION_X
, TRY_TO_DOUBLE(AVIATION) AS AVIATION
, TRY_TO_DOUBLE(GROUND) AS GROUND_X
, TRY_TO_DOUBLE(GROUND) AS GROUND
, TRY_TO_DOUBLE(MARINE) AS MARINE_X
, TRY_TO_DOUBLE(MARINE) AS MARINE
, TRY_TO_DOUBLE(CUSTOMS_EFFICIENCY) AS CUSTOMS_EFFICIENCY_X
, TRY_TO_DOUBLE(CUSTOMS_EFFICIENCY) AS CUSTOMS_EFFICIENCY
, TRY_TO_DOUBLE(CARGO_THEFT) AS CARGO_THEFT_X
, TRY_TO_DOUBLE(CARGO_THEFT) AS CARGO_THEFT
, TRY_TO_NUMBER(PERSONAL_FREEDOM,38,0 ) AS PERSONAL_FREEDOM_X
, TRY_TO_NUMBER(PERSONAL_FREEDOM,38,0) AS PERSONAL_FREEDOM
, TRY_TO_NUMBER(WORKERS_RIGHTS,38,0 ) AS WORKERS_RIGHTS_X
, TRY_TO_NUMBER(WORKERS_RIGHTS,38,0) AS WORKERS_RIGHTS
, TRY_TO_NUMBER(CHILD_LABOUR,38,0 ) AS CHILD_LABOUR_X
, TRY_TO_NUMBER(CHILD_LABOUR,38,0) AS CHILD_LABOUR
, TRY_TO_NUMBER(ENVIRONMENT,38,0 ) AS ENVIRONMENT_X
, TRY_TO_NUMBER(ENVIRONMENT,38,0) AS ENVIRONMENT
, DEATH_AND_INJURY
, DETENTION_AND_DISCRIMINATION
, KIDNAP_AND_RANSOM
, SUPPLY_WATCH_COMPANY_NAME
, CURRENT_TIMESTAMP() AS LOAD_DATE
, CASE
 WHEN (RISK_EXPOSURE_INDEX_X is null and RISK_EXPOSURE_INDEX is not null) THEN 'ERROR IN RISK_EXPOSURE_INDEX COLUMN'
 WHEN (NATURAL_DISASTER_INDEX_X is null and NATURAL_DISASTER_INDEX is not null) THEN 'ERROR IN NATURAL_DISASTER_INDEX COLUMN'
 WHEN (LONGITUDE_X is null and LONGITUDE is not null) THEN 'ERROR IN LONGITUDE COLUMN'
 WHEN (LATITUDE_X is null and LATITUDE is not null) THEN 'ERROR IN LATITUDE COLUMN'
 WHEN (FLOOD_X is null and FLOOD is not null) THEN 'ERROR IN FLOOD COLUMN'
 WHEN (FLASH_FLOOD_X is null and FLASH_FLOOD is not null) THEN 'ERROR IN FLASH_FLOOD COLUMN'
 WHEN (WAR_X is null and WAR is not null) THEN 'ERROR IN WAR COLUMN'
 WHEN (TERRORISM_X is null and TERRORISM is not null) THEN 'ERROR IN TERRORISM COLUMN'
 WHEN (CIVIL_UNREST_X is null and CIVIL_UNREST is not null) THEN 'ERROR IN CIVIL_UNREST COLUMN'
 WHEN (OPERATIONAL_INDEX_X is null and OPERATIONAL_INDEX is not null) THEN 'ERROR IN OPERATIONAL_INDEX COLUMN'
 WHEN (POLITICAL_VIOLENCE_INDEX_X is null and POLITICAL_VIOLENCE_INDEX is not null) THEN 'ERROR IN POLITICAL_VIOLENCE_INDEX COLUMN'
 WHEN (SOCIO_POLITICAL_INDEX_X is null and SOCIO_POLITICAL_INDEX is not null) THEN 'ERROR IN SOCIO_POLITICAL_INDEX COLUMN'
 WHEN (SUSTAINABILITY_INDEX_X is null and SUSTAINABILITY_INDEX is not null) THEN 'ERROR IN SUSTAINABILITY_INDEX COLUMN'
 WHEN (RISK_TO_INDIVIDUALS_INDEX_X is null and RISK_TO_INDIVIDUALS_INDEX is not null) THEN 'ERROR IN RISK_TO_INDIVIDUALS_INDEX COLUMN'
 WHEN (EARTHQUAKE_X is null and EARTHQUAKE is not null) THEN 'ERROR IN EARTHQUAKE COLUMN'
 WHEN (TORNADO_X is null and TORNADO is not null) THEN 'ERROR IN TORNADO COLUMN'
 WHEN (VOLCANO_X is null and VOLCANO is not null) THEN 'ERROR IN VOLCANO COLUMN'
 WHEN (EXTRATROPICAL_CYCLONE_X is null and EXTRATROPICAL_CYCLONE is not null) THEN 'ERROR IN EXTRATROPICAL_CYCLONE COLUMN'
 WHEN (HAIL_X is null and HAIL is not null) THEN 'ERROR IN HAIL COLUMN'
 WHEN (TROPICAL_CYCLONE_X is null and TROPICAL_CYCLONE is not null) THEN 'ERROR IN TROPICAL_CYCLONE COLUMN'
 WHEN (LIGHTNING_X is null and LIGHTNING is not null) THEN 'ERROR IN LIGHTNING COLUMN'
 WHEN (WILDFIRE_X is null and WILDFIRE is not null) THEN 'ERROR IN WILDFIRE COLUMN'
 WHEN (TSUNAMI_X is null and TSUNAMI is not null) THEN 'ERROR IN TSUNAMI COLUMN'
 WHEN (STORM_SURGE_X is null and STORM_SURGE is not null) THEN 'ERROR IN STORM_SURGE COLUMN'
 WHEN (CORRUPTION_X is null and CORRUPTION is not null) THEN 'ERROR IN CORRUPTION COLUMN'
 WHEN (LAW_ENFORCEMENT_X is null and LAW_ENFORCEMENT is not null) THEN 'ERROR IN LAW_ENFORCEMENT COLUMN'
 WHEN (COUNTERFEIT_THREAT_X is null and COUNTERFEIT_THREAT is not null) THEN 'ERROR IN COUNTERFEIT_THREAT COLUMN'
 WHEN (AVIATION_X is null and AVIATION is not null) THEN 'ERROR IN AVIATION COLUMN'
 WHEN (GROUND_X is null and GROUND is not null) THEN 'ERROR IN GROUND COLUMN'
 WHEN (MARINE_X is null and MARINE is not null) THEN 'ERROR IN MARINE COLUMN'
 WHEN (CUSTOMS_EFFICIENCY_X is null and CUSTOMS_EFFICIENCY is not null) THEN 'ERROR IN CUSTOMS_EFFICIENCY COLUMN'
 WHEN (CARGO_THEFT_X is null and CARGO_THEFT is not null) THEN 'ERROR IN CARGO_THEFT COLUMN'
 WHEN (PERSONAL_FREEDOM_X is null and PERSONAL_FREEDOM is not null) THEN 'ERROR IN PERSONAL_FREEDOM COLUMN'
 WHEN (WORKERS_RIGHTS_X is null and WORKERS_RIGHTS is not null) THEN 'ERROR IN WORKERS_RIGHTS COLUMN'
 WHEN (CHILD_LABOUR_X is null and CHILD_LABOUR is not null) THEN 'ERROR IN CHILD_LABOUR COLUMN'
 WHEN (ENVIRONMENT_X is null and ENVIRONMENT is not null) THEN 'ERROR IN ENVIRONMENT COLUMN'
 ELSE NULL
                        END AS ERROR

 FROM {{source('csccore', 'es_nodes_stg')}}