
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'tpch'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'tpch'
# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]



target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
    - "dbt_packages"

on-run-start:
  - "alter warehouse transforming set warehouse_size=small;"
  #- "{{dbt_meta_testing.required_tests()}}"
  # - '{{create_udfs()}}' # comment / uncomment this line to build UDFs called in the create_udfs macro

on-run-end:
  - "alter warehouse transforming set warehouse_size=xsmall;"
  - "{{ grant_all_on_schemas(schemas, 'transformer') }}"

vars:
  start_date: '1999-01-01'
  'dbt_date:time_zone': 'Europe/Frankfurt'

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models


# in dbt_project.yml
models:  
        
  tpch:
    
    demo_examples:
      audit:
        #+post-hook: 
          #- "{{validate_model_name(this, ruleset='demos')}}"
          #- "{{validate_column_names(this)}}"

    marts:
      bronze:
        +materialized: view
      gold:
        materialized: table
        +required_docs: true
        +required_tests:
          "unique": 1
          "not_null": 1
        
        fct_orders:
          +required_tests:
            "orders__assert_positive_price": 1
            
# seeds:
#   tpch:
#     snowflake_contract_rates:
#       +column_types:
#         effective_date: DATE
#         rate: NUMBER   