
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'snowflake_hub'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'snowflake_hub'
# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
    - "dbt_packages"

on-run-start:
  - "alter warehouse transforming set warehouse_size=small;"

on-run-end:
  - "alter warehouse transforming set warehouse_size=xsmall;"
  - "{{ grant_all_on_schemas(schemas, 'transformer') }}"

vars:
  start_date: '2023-01-01'
  'dbt_date:time_zone': 'America/Denver'
  demo__backfill_incremental__start_date: '1998-07-20'
  demo__backfill_incremental__end_date: '1998-08-02'

models:
  snowflake_hub:
    raw:
      +materialized: view

    marts:
      +group: matts_awesome_group_name 
        
      intermediate:
        +materialized: view
      consumption:
        +materialized: table
        core:
          +required_docs: true
          +required_tests:
            "unique": 1
            "not_null": 1
        
          fct_orders:
            +required_tests:
              "orders__assert_positive_price": 1

  #dbt_project_evaluator:
  #  +database: dbt_project_evaluator
  #  +schema: snowflake_hub